# PostgreSQL via testcontainers (Integration Tests)
spring.datasource.url=jdbc:tc:postgresql:latest:///test
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
